### ISSUE TITLE
Need sample for webhook with re-requesting event for security

### ISSUE THREAD

**Issue by BitpopCoin** [chargebee/chargebee-samples#3]
PHP

**Comment by saravana-cb** [comment]
Could you explain little more about your query?

**Comment by BitpopCoin** [comment]
https://github.com/chargebee/chargebee-samples/blob/master/php/php_src/WebhookHandler.php

with

https://apidocs.chargebee.com/docs/api/events#retrieve_an_event

**Comment by saravana-cb** [comment]
Hi,
Assuming that you are looking to validate the webhook content received, you could use https for your webhook URL. Alternatively, you can call the Retrieve Event API once you receive the webhook, however this might cause delay, resulting in a timeout error in Chargebee if we do not receive the webhook response.
